- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: install snap and certbot
      command: "{{item}}"
      with_items:
        - snap install core
        - snap refresh core
        - snap install --classic certbot
    - name: Create symbolic link 
      file:
        src: "/snap/bin/certbot"
        dest: "/usr/bin/certbot"
        state: link
    - name: install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
        update_cache: yes
    - name: update dns records
      command: "{{item}}"
      become_user: boyko
      with_items:
        - sh /home/boyko/ansible/cloudflare/creatednsrecord.sh {{ lookup('ansible.builtin.env', 'CF_TOKEN') }} {{ lookup('ansible.builtin.env', 'IP') }} *.devopstrain.eu
        - sh /home/boyko/ansible/cloudflare/creatednsrecord.sh {{ lookup('ansible.builtin.env', 'CF_TOKEN') }} {{ lookup('ansible.builtin.env', 'IP') }} devopstrain.eu     
    - name: Pause for 2 minutes to wait for dns propagation
      ansible.builtin.pause:
        minutes: 2
    - name: Generate certificates 
      command: certbot --noninteractive --agree-tos --cert-name devopstrain.eu -d devopstrain.eu --register-unsafely-without-email --nginx 
    - name: generate SSH key
      become_user: boyko
      shell:
        cmd: printf '\ny\n\n\n' | ssh-keygen -t rsa -P ""
        chdir: /home/boyko/    
    - name: check and create deploy key for repo
      command: "{{item}}"
      become_user: boyko
      with_items:
        - sh /home/boyko/ansible/github/createdeploykey.sh
    - name: Clone a github repository
      become_user: boyko
      shell:
        cmd: rm -rf dev && ssh-keyscan github.com >> ~/.ssh/known_hosts && git clone -b dev git@github.com:bobn3n/testrepo.git dev
        chdir: /home/boyko/
