name: Terraform Apply for Azure
on: workflow_dispatch

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
      
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }} 8ec181e6-4a2c-4511-92ce-fbd7ac04237e
        tenant-id: ${{ secrets.AZURE_TENANT_ID }} 75be9c20-d181-496f-84b7-e2e3c573e467
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} affa400c-9132-43d6-b147-841e4a5b033f
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          # You can write your Azure CLI inline scripts here.