name: Terraform Apply for Azure
on: workflow_dispatch

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read
      
jobs: 
  deploy_site:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }} 
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          RESOURCE_GROUP_NAME=rg_tfstate
          STORAGE_ACCOUNT_NAME=tfstate$RANDOM
          CONTAINER_NAME=tfstate

          az group create \
          --name $RESOURCE_GROUP_NAME \
          --location westeurope

          az storage account create \
          --resource-group $RESOURCE_GROUP_NAME \
          --name $STORAGE_ACCOUNT_NAME \
          --sku Standard_LRS \
          --encryption-services blob

          az storage container create \
          --name $CONTAINER_NAME \
          --account-name $STORAGE_ACCOUNT_NAME

          ACCOUNT_KEY=$(
          az storage account keys list 
          --resource-group $RESOURCE_GROUP_NAME 
          --account-name $STORAGE_ACCOUNT_NAME 
          --query '[0].value' -o tsv)
          
          export ARM_ACCESS_KEY=$ACCOUNT_KEY


    - name: Checkout the repository to the runner
      uses: actions/checkout@v2
    
    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
    
    - name: Terraform init
      id: init
      run: terraform init 
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform plan
      id: plan
      run: terraform plan -no-color -input=false
      continue-on-error: true
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -input=false
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Shell Script that runs Ansible Playbook
      run: ./ssh_vm.sh 
      env:
        CF_TOKEN: ${{ secrets.CF_TOKEN }}
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}